apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-master-2
  labels:
    app: redis
    role: master
    tier: backend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: redis
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
